meta_product_name: "Heliast"
meta_title: "Heliast | Overcome Indecision"
meta_description: "Tu es indécis ? Tu hésites entre plusieurs choix ? Heliast te permet de déléguer tes indécions à des inconnus. Toi aussi prends des décisions pour les autres et gagne des points pour devenir l'Héliaste ultime !"
meta_image: "heliast-cover.jpg"
twitter_account: "@offbattaglia"   # required for Twitter Cards
